runtime: python
env: flex

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.13"

entrypoint: streamlit run app.py --server.port $PORT

automatic_scaling:
    max_num_instances: 1
    
handlers:
  - url: /.*
    script: auto
