[theme]
primaryColor = "#D32F2F"            # red accents
backgroundColor = "#FFFFFF"         # white background
secondaryBackgroundColor = "#F8F9FA"  # light gray panels
textColor = "#000000"               # black text
font = "sans serif"

[client]
toolbarMode = "minimal"